name: MSTR_MobDifficulty
main: ca.strendin.MSTR_MobDifficulty.MSTR_MobDifficulty
version: 0.1
author: Mark Strendin
description: Configurable difficulty modifiers for mobs

permissions:
  mstr_mobdifficulty.hardmode.one:
    description: Hardmode level one
    default: false
  mstr_mobdifficulty.hardmode.two:
    description: Hardmode level one
    default: false
  mstr_mobdifficulty.hardmode.three:
    description: Hardmode level one
    default: false
  mstr_mobdifficulty.easymode.one:
    description: Easymode level one
    default: false
  mstr_mobdifficulty.easymode.two:
    description: Easymode level one
    default: false
  mstr_mobdifficulty.easymode.three:
    description: Easymode level one
    default: false
  mstr_mobdifficulty.debug:
    default: false
    
commands:  
  diff:
    description: Displays what difficulty modifier is used for your player